services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dookie_tv_pipeline
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./assets:/app/assets
    restart: "no"
