"""
Pipeline Step 3.1: DeepSeek Script & Metadata Generator
Calls DeepSeek V4 Flash API to generate structured multi-shot JSON scripts for YouTube Shorts (12 to 15 seconds total).
Uses the Multi-Shot Animation Prompt Framework for Segmind Seedance 2.0 with explicit, uncompressed event timing.
"""

import os
import json
import logging
import requests
from typing import List, Dict, Any, Tuple
from dataclasses import dataclass

logger = logging.getLogger(__name__)

DEEPSEEK_API_URL = "https://api.deepseek.com/chat/completions"


@dataclass
class SubtitleItem:
    start: float
    end: float
    text: str


@dataclass
class ShortScript:
    title: str
    description: str
    tags: List[str]
    mascot: str
    topic: str
    animation_prompt: str
    narration_text: str
    subtitles: List[SubtitleItem]
    total_duration_seconds: float = 15.0


class ScriptGenerator:
    def __init__(self, api_key: str | None = None):
        self.api_key = api_key or os.getenv("DEEPSEEK_API_KEY")

    def _build_system_prompt(self) -> str:
        framework_path = os.path.abspath("config/multi_shot_prompt_framework.md")
        framework_text = ""
        if os.path.exists(framework_path):
            with open(framework_path, "r", encoding="utf-8") as f:
                framework_text = f.read()

        return (
            "You are an expert children's content creator and cinematic prompt engineer writing multi-shot animation prompts for YouTube Shorts.\n"
            "Channel: Dookie Tv. Audience: Toddlers and young kids (2-6 years old).\n"
            "Visual Style: 3D Pixar animated cartoon style, stylized cute 3D character, smooth 3D render. Palette: Sunshine Yellow #FFD166, Sky Blue #4EA8DE, Bubblegum Pink #EF476F. NO realistic photo animals.\n\n"
            f"MULTI-SHOT PROMPT FRAMEWORK DOCUMENT:\n{framework_text}\n\n"
            "ADDITIONAL SYSTEM RULES:\n"
            "1. Total Video Duration: EXACTLY 10.0 seconds total.\n"
            "2. Multi-Shot Sequence: Divide video into 2 distinct timecoded shots (5s each): [00:00 - 00:05] and [00:05 - 00:10].\n"
            "3. Per-Shot Specs: Each shot MUST specify 4 camera parameters: Shot size (Wide/Medium/Close-up/Macro), Lens (24mm/35mm/50mm/85mm), Camera Angle (Low angle/High angle/Eye-level), Camera Movement (Push in/Pull out/Track/Orbit/Pan/Tilt/Static).\n"
            "4. Mascot Binding: Every mascot reference MUST state: '[Mascot], the mascot character from image 1 and image 2...'\n"
            "5. EXPLICIT UNCOMPRESSED EVENT DETAIL: NEVER use vague summaries like 'sequentially', 'numbers 1 to 10 pop up', or 'etc.'. EVERY SINGLE visual element must be explicitly named (e.g., 'At 00:01 3D number 1 pops up. At 00:03 3D number 2 pops up. At 00:06 3D number 3 pops up').\n"
            "6. EXPLICIT SPOKEN DIALOGUE SYNC: EVERY SINGLE spoken word must be written inside speech marks in the shot paragraph where it lands (e.g. off-screen child voice narrates \"One!\", off-screen child voice narrates \"Two!\", off-screen child voice narrates \"Three!\").\n"
            "7. REALISTIC TIMING BUDGET: In a 10-second video, limit interactive items to 2 to 3 items max (e.g., counting 1 to 3, or 2 distinct colors/shapes) so each item gets 3-5 seconds for visual pop and narration sync.\n"
            "8. Mascot SFX & Mouth Opening Sync: Mascots NEVER speak human words. Whenever the mascot makes an animal sound effect (woof/bark/meow/squeak), the prompt MUST explicitly detail the visual mouth opening action at that exact timestamp (e.g. 'At 00:03, Dookie opens his mouth wide and barks happy puppy woofs, mouth movement and barking sound synchronized frame-by-frame. NO mascot human speech.').\n"
            "9. NO AI Text on Screen: Mandate inside prompt: 'NO on-screen text, NO subtitles, NO captions generated by AI. Clean 3D video frames only.'\n"
            "10. Metadata Footer: Prompt MUST end with:\n"
            "   Location: [Location], [Time of day].\n"
            "   Audio: Off-screen friendly child narrator voice matching vocal_reference.mp3, upbeat cheerful children's background music matching music_reference.mp3, mascot species-specific SFX only (NO mascot human speech).\n"
            "11. Prompt Length Limit: Entire animation_prompt MUST be 1,500 characters or fewer.\n"
            "12. Metadata Rules: Title < 100 chars (NO '| Dookie Tv', max 2 hashtags). Description with #kids #shorts #dookietv.\n"
            "13. Output valid JSON ONLY adhering to the requested schema."
        )

    def _build_user_prompt(self, topic: str, mascot: str) -> str:
        clean_topic = topic.replace("_", " ")
        mascot_cap = mascot.capitalize()
        sfx_desc = "happy barks and puppy woofs" if mascot.lower() == "dookie" else ("sweet meows and purrs" if mascot.lower() == "mia" else "soft squeaks and carrot crunching")

        return (
            f"Generate a multi-shot Short script (10.0 seconds total) featuring mascot '{mascot_cap}' teaching topic '{clean_topic}'.\n"
            "Respond ONLY with a JSON object containing the following keys:\n"
            "{\n"
            '  "title": "' + mascot_cap + ' Learns ' + clean_topic.capitalize() + '! 🎨 #learning #' + topic.split("_")[0] + '",\n'
            '  "description": "Join ' + mascot_cap + ' on Dookie Tv as we learn about ' + clean_topic + '! #' + topic + ' #learning #kids #shorts #dookietv",\n'
            '  "tags": ["kids", "shorts", "learning", "' + topic + '", "dookietv"],\n'
            '  "total_duration_seconds": 10.0,\n'
            '  "animation_prompt": "[00:00 - 00:05] Wide, 24mm, eye-level, track — ' + mascot_cap + ', the mascot character from image 1 and image 2, sits happily in a bright playroom with a sunshine yellow background (#FFD166). At 00:02, a glowing 3D number 1 pops up beside him, off-screen child voice narrates \\"One!\\". ' + mascot_cap + ' waves excitedly with a big smile.\\n\\n[00:05 - 00:10] Medium, 50mm, high angle, push in — At 00:06, a glowing sky blue 3D number 2 pops up, off-screen child voice narrates \\"Two!\\". At 00:08, a glowing bubblegum pink 3D number 3 pops up, off-screen child voice narrates \\"Three!\\". ' + mascot_cap + ' tilts head playfully. NO on-screen text, NO subtitles, NO AI captions.\\n\\nLocation: Bright colorful playroom, sunny morning.\\nAudio: Off-screen friendly child narrator voice matching vocal_reference.mp3, upbeat cheerful children\'s background music matching music_reference.mp3, mascot ' + sfx_desc + ' (NO mascot human speech).",\n'
            '  "narration_text": "One! Two! Three!",\n'
            '  "subtitles": [\n'
            '    {"start": 0.0, "end": 5.0, "text": "One!"},\n'
            '    {"start": 5.0, "end": 8.0, "text": "Two!"},\n'
            '    {"start": 8.0, "end": 10.0, "text": "Three!"}\n'
            '  ]\n'
            "}"
        )

    def calculate_cost(self, usage: Dict[str, Any]) -> float:
        """
        Calculates exact DeepSeek V4 Flash API cost:
        - 1M Input Tokens (Cache Hit): $0.0028 ($0.0000000028/token)
        - 1M Input Tokens (Cache Miss): $0.14 ($0.00000014/token)
        - 1M Output Tokens: $0.28 ($0.00000028/token)
        """
        if not usage:
            return 0.0005

        prompt_cache_hit = usage.get("prompt_cache_hit_tokens", 0)
        prompt_cache_miss = usage.get("prompt_cache_miss_tokens", usage.get("prompt_tokens", 0) - prompt_cache_hit)
        completion_tokens = usage.get("completion_tokens", 0)

        hit_cost = prompt_cache_hit * (0.0028 / 1_000_000)
        miss_cost = max(0, prompt_cache_miss) * (0.14 / 1_000_000)
        output_cost = completion_tokens * (0.28 / 1_000_000)

        return hit_cost + miss_cost + output_cost

    def generate_script(self, topic: str, mascot: str, mock_mode: bool = True) -> Tuple[ShortScript, float]:
        """
        Generates a multi-shot video script using DeepSeek API or mock fallback, returning (script, cost).
        """
        clean_topic = topic.replace("_", " ")
        topic_tag = topic.replace("_", "")
        mascot_cap = mascot.capitalize()
        sfx_desc = "happy barks and puppy woofs" if mascot.lower() == "dookie" else ("sweet meows and purrs" if mascot.lower() == "mia" else "soft squeaks and carrot crunching")

        if mock_mode or not self.api_key:
            logger.info(f"[MOCK] ScriptGenerator: Generating multi-shot script for mascot '{mascot}' & topic '{topic}'")
            mock_prompt = (
                f"[00:00 - 00:05] Wide, 24mm, eye-level, track — {mascot_cap}, the mascot character from image 1 and image 2, "
                f"sits happily in a bright playroom with a sunshine yellow background (#FFD166). At 00:02, a glowing 3D number 1 pops up beside him, "
                f'off-screen child voice narrates "One!". {mascot_cap} waves excitedly.\n\n'
                f"[00:05 - 00:10] Medium, 50mm, high angle, push in — At 00:06, a glowing sky blue 3D number 2 pops up, "
                f'off-screen child voice narrates "Two!". At 00:08, a glowing bubblegum pink 3D number 3 pops up, '
                f'off-screen child voice narrates "Three!". {mascot_cap} tilts head playfully.\n\n'
                f"[00:10 - 00:15] Close-up, 85mm, low angle, static — {mascot_cap} smiles bright as 3D numbers 1, 2, and 3 bounce rhythmically around him. "
                "NO on-screen text, NO subtitles, NO AI captions.\n\n"
                "Location: Bright colorful playroom, sunny morning.\n"
                f"Audio: Off-screen friendly child narrator voice, upbeat cheerful children's background music, mascot {sfx_desc} (NO mascot human speech)."
            )
            mock_script = ShortScript(
                title=f"{mascot_cap} Learns {clean_topic.capitalize()}! 🎨 #learning #{topic_tag}",
                description=f"Join {mascot_cap} on Dookie Tv as we learn about {clean_topic}! #{topic_tag} #learning #kids #shorts #dookietv",
                tags=["kids", "shorts", "learning", mascot.lower(), topic.lower()],
                mascot=mascot,
                topic=topic,
                animation_prompt=mock_prompt,
                narration_text="One! Two! Three!",
                subtitles=[
                    SubtitleItem(start=0.0, end=5.0, text="One!"),
                    SubtitleItem(start=5.0, end=8.0, text="Two!"),
                    SubtitleItem(start=8.0, end=15.0, text="Three!"),
                ],
                total_duration_seconds=15.0,
            )
            return mock_script, 0.0005

        logger.info(f"Connecting to DeepSeek API for mascot '{mascot}' & topic '{topic}' (Multi-Shot mode)...")
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": "deepseek-chat",
            "messages": [
                {"role": "system", "content": self._build_system_prompt()},
                {"role": "user", "content": self._build_user_prompt(topic, mascot)},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.7,
        }

        try:
            response = requests.post(DEEPSEEK_API_URL, headers=headers, json=payload, timeout=30)
            response.raise_for_status()
            res_data = response.json()
            content = res_data["choices"][0]["message"]["content"]
            parsed_json = json.loads(content)
            
            usage = res_data.get("usage", {})
            real_cost = self.calculate_cost(usage)

            sub_list = []
            for item in parsed_json.get("subtitles", []):
                sub_list.append(
                    SubtitleItem(
                        start=float(item.get("start", 0.0)),
                        end=float(item.get("end", 5.0)),
                        text=str(item.get("text", "")),
                    )
                )
            if not sub_list:
                narration = parsed_json.get("narration_text", f"Let's learn {clean_topic}!")
                sub_list = [
                    SubtitleItem(start=0.0, end=5.0, text=narration[:30]),
                    SubtitleItem(start=5.0, end=10.0, text=narration[30:60] if len(narration) > 30 else "Fun learning!"),
                    SubtitleItem(start=10.0, end=15.0, text="Dookie Tv!"),
                ]

            raw_title = parsed_json.get("title", f"{mascot_cap} Short")
            clean_title = raw_title.replace("| Dookie Tv", "").replace("| Dookie TV", "").strip()

            script = ShortScript(
                title=clean_title,
                description=parsed_json.get("description", f"Join {mascot_cap} for fun learning! #{topic_tag} #learning #kids #shorts #dookietv"),
                tags=parsed_json.get("tags", ["kids", "shorts", "learning"]),
                mascot=mascot,
                topic=topic,
                animation_prompt=parsed_json.get("animation_prompt", ""),
                narration_text=parsed_json.get("narration_text", ""),
                subtitles=sub_list,
                total_duration_seconds=float(parsed_json.get("total_duration_seconds", 15.0)),
            )
            return script, real_cost
        except Exception as e:
            logger.error(f"Error calling DeepSeek API: {e}. Falling back to mock script.")
            raise e
